fix: use relative path for Rive asset import to fix Metro bundler error
Changed from '@/assets/rive/...' to '../../../assets/rive/...'

Metro bundler couldn't resolve the @ alias for assets directory.
Using relative path from gamification/ui/celebrations/ to assets/rive/

Error: Unable to resolve "@/assets/rive/streak_flame.riv"
Fixed: Using relative path "../../../assets/rive/streak_flame.riv"